spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/libraryapidb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

flyway:
  locations: classpath:db/migration
  
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}